24 masterid
utsw-bicf/cognitionexplorer pull request #29
Opened 2020-06-05 03:46 UTC by SenseCode

Close #24. 
![image](https://user-images.githubusercontent.com/38848214/83834877-fdc39980-a6b4-11ea-9afa-d2960a3789d3.png)
![image](https://user-images.githubusercontent.com/38848214/83834906-0f0ca600-a6b5-11ea-9ee3-ddc7cdf30f6e.png)
![image](https://user-images.githubusercontent.com/38848214/83834948-251a6680-a6b5-11ea-816c-9b46d949ebe1.png)

2020-06-09 16:32 UTC, vsmalladi requested changes
Add number for radio button options

Example:

"pic": {
            "title": "Patient Initial Category",
            "description": "Which catagory patient belong to",
            "type": "string",
            "enum": [
                "1 ADC Core",
                "2 Consult",
                "3 Research Only",
                "4 Control",
                "5 ADC relative",
                "6 autopsy only",
                "7 Autopsied demented relative of ADC patient",
                "8 Autopsied non-demented relative of ADC patient",
                "9 Autopsied/non-clinic/control",
                "99 Unknown/not done"
            ]
        },

2020-06-12 05:31 UTC, SenseCode commented
Please update if state enum(without numbers ) doesn't work...I checked both of the codebook and the export files, should work without double write the state name or numbers. @vsmalladi...

2020-06-12 05:32 UTC, SenseCode commented
> Add number for radio button options
> 
> Example:
> 
> "pic": {
> "title": "Patient Initial Category",
> "description": "Which catagory patient belong to",
> "type": "string",
> "enum": [
> "1 ADC Core",
> "2 Consult",
> "3 Research Only",
> "4 Control",
> "5 ADC relative",
> "6 autopsy only",
> "7 Autopsied demented relative of ADC patient",
> "8 Autopsied non-demented relative of ADC patient",
> "9 Autopsied/non-clinic/control",
> "99 Unknown/not done"
> ]
> },

2020-06-19 21:24 UTC, vsmalladi approved these changes

2020-06-19 21:24 UTC, merged